spring.application.name=tracker
spring.data.mongodb.uri=mongodb://localhost:27017/event_engagement
logging.level.org.mongodb.driver.protocol.command=DEBUG
logging.level.org.mongodb.driver.protocol.query=DEBUG
logging.level.org.mongodb.driver=DEBUG
